// Contenu du site (français). RÈGLES DE LA FAMILLE :
//  • les hôtels / la croisière restent une SURPRISE : jamais de nom d'hôtel, de croisière ou de resort ici ;
//  • aucun prix, aucun montant payé ;
//  • horaires = heure locale. Mettre « à confirmer » tant que ce n'est pas sûr.
window.VOYAGE = {
  debut: "2026-12-11",
  fin: "2026-12-27",
  voyageurs: "Fanny, Maman & Quentin",

  pays: {
    fr: { nom: "France", couleur: "#4a5f86", drapeau: "🇫🇷" },
    sg: { nom: "Singapour", couleur: "#d6334a", drapeau: "🇸🇬" },
    vn: { nom: "Vietnam", couleur: "#d99a06", drapeau: "🇻🇳" },
    th: { nom: "Thaïlande", couleur: "#2a6fb8", drapeau: "🇹🇭" },
  },

  // Les étapes (carte + cartes postales)
  etapes: [
    { id: "sg", pays: "sg", nom: "Singapour", dates: "13 – 16 déc.", nuits: 3, lat: 1.2834, lon: 103.8607, img: "supertrees",
      texte: "La ville-jardin de Fanny : serres géantes, gratte-ciel au bord de l’eau et les meilleurs stands de rue d’Asie." },
    { id: "hn", pays: "vn", nom: "Hanoï", dates: "16 déc.", nuits: 1, lat: 21.0285, lon: 105.8542, img: "hanoi-old-quarter",
      texte: "Le vieux quartier et ses « 36 rues », le lac Hoàn Kiếm, les marionnettes sur l’eau." },
    { id: "hl", pays: "vn", nom: "Baie d’Along", dates: "17 – 18 déc.", nuits: 1, lat: 20.9101, lon: 107.0476, img: "halong",
      texte: "Une nuit à bord, entre près de deux mille pitons calcaires sortis de l’eau émeraude." },
    { id: "ha", pays: "vn", nom: "Hội An", dates: "18 – 20 déc.", nuits: 2, lat: 15.8801, lon: 108.338, img: "hoian-lanterns",
      texte: "L’ancien port aux maisons jaunes, qui s’illumine de lanternes à la nuit tombée." },
    { id: "pa", pays: "th", nom: "Phuket · Patong", dates: "20 – 22 déc.", nuits: 2, lat: 7.8964, lon: 98.2961, img: "patong",
      texte: "Deux jours de plage et de soleil sur la côte ouest de Phuket." },
    { id: "ky", pays: "th", nom: "Koh Yao Yai", dates: "22 – 25 déc.", nuits: 3, lat: 8.0, lon: 98.6, img: "koh-yao-yai",
      texte: "Une île verte et paisible face aux pitons de la baie de Phang Nga. Noël les pieds dans le sable." },
  ],

  // Ordre du trajet sur la carte : [id étape, mode du trajet vers la suivante]
  trajet: [
    { de: "sg", vers: "hn", mode: "avion" },
    { de: "hn", vers: "hl", mode: "route" },
    { de: "hl", vers: "ha", mode: "avion" },
    { de: "ha", vers: "pa", mode: "avion" },
    { de: "pa", vers: "ky", mode: "bateau" },
  ],

  // Jour par jour. nuit = description sans nom d'hôtel.
  jours: [
    { d: "2026-12-11", pays: "fr", etape: "Paris", titre: "Quentin monte à Paris", cle: "🚆 18h50 → 22h04",
      resume: "Première étape pour Quentin : train du soir, puis une nuit à Paris avant le grand départ.",
      items: [
        { k: "train", h: "18h50", t: "Montpellier → Paris Gare de Lyon", p: "Arrivée à 22h04. Dîner dans le train, l’hôtel est juste en face de la gare." },
        { k: "nuit", t: "Nuit à Paris, juste en face de la gare de Lyon." },
      ] },
    { d: "2026-12-12", pays: "fr", etape: "Roissy", titre: "En route pour l’Asie", cle: "✈️ 22h20 Paris → Singapour",
      resume: "Train pour Maman, RER pour Quentin, et décollage pour la nuit.",
      items: [
        { k: "train", h: "10h39", t: "Maman : Lorraine TGV → aéroport CDG", p: "Arrivée à 12h00 à la gare TGV de Roissy." },
        { k: "train", t: "Quentin : Paris → Roissy par le RER B", p: "Compter environ 1 heure depuis le centre." },
        { k: "vol", h: "22h20", t: "Paris CDG → Singapour", p: "Vol de nuit, arrivée le lendemain à 18h05." },
        { k: "nuit", t: "Nuit dans l’avion." },
      ] },
    { d: "2026-12-13", pays: "sg", etape: "Singapour", titre: "Arrivée à Singapour", img: "marina-bay", cle: "🛬 18h05 · Changi",
      resume: "Fanny vous attend à la sortie. Dîner léger, puis au lit : le décalage horaire se fait sentir.",
      items: [
        { k: "vol", h: "18h05", t: "Atterrissage à Changi", p: "Souvent élu meilleur aéroport du monde : l’immigration est rapide. Fanny est là !" },
        { k: "taxi", h: "~19h00", t: "Taxi vers le centre", p: "Environ 25 minutes jusqu’au centre-ville." },
        { k: "repas", t: "Dîner simple tout près de l’hôtel", p: "Un bol de nouilles ou un plat de riz, puis dodo." },
        { k: "nuit", t: "Nuit à l’hôtel, dans le centre." },
      ] },
    { d: "2026-12-14", pays: "sg", etape: "Singapour", titre: "Jardins & Marina Bay", img: "cloud-forest", cle: "🌳 Gardens by the Bay",
      note: "Programme proposé : on ajustera selon la fatigue et la météo.",
      resume: "Des serres géantes à l’abri de la chaleur, puis les Supertrees qui s’allument à la nuit tombée.",
      items: [
        { k: "repas", h: "Matin", t: "Petit-déjeuner local", p: "Kaya toast, café et œufs mollets, puis balade au bord de la baie avant la chaleur de midi." },
        { k: "visite", h: "Après-midi", t: "Gardens by the Bay : Cloud Forest & Flower Dome", p: "Deux serres géantes et climatisées. Le Cloud Forest est une montagne couverte de végétation avec une cascade intérieure de plus de 30 mètres, que l’on parcourt par des passerelles suspendues. Le Flower Dome change de décor à chaque saison : à Noël, il est décoré pour les fêtes." },
        { k: "spectacle", h: "~19h45", t: "Les Supertrees s’illuminent", p: "Au Supertree Grove, les arbres métalliques géants s’allument en musique pendant le spectacle gratuit « Garden Rhapsody » (généralement vers 19h45 et 20h45). On le regarde allongé sur les bancs." },
        { k: "repas", h: "Soir", t: "Dîner au 33e étage : Level 33", p: "Une brasserie artisanale tout en haut d’une tour de Marina Bay : bières brassées sur place, terrasse sur toute la baie et vue sur le Marina Bay Sands. Jour à confirmer." },
      ] },
    { d: "2026-12-15", pays: "sg", etape: "Singapour", titre: "Quartiers, hawkers & hotpot", img: "hawker", cle: "🍜 Hawker centre · Clarke Quay",
      note: "Programme proposé : on choisira sur place.",
      resume: "Chinatown, Little India et Kampong Glam en une matinée, un déjeuner de hawker, un hotpot le soir.",
      items: [
        { k: "visite", h: "Matin", t: "Chinatown, Little India, Kampong Glam", p: "Temples chinois et hindous, mosquée du Sultan, shophouses colorées : en quelques heures, on passe d’une culture à l’autre." },
        { k: "repas", h: "Midi", t: "Un hawker centre, l’âme de Singapour", p: "Des dizaines de stands sous un même toit : riz au poulet hainanais, laksa, satay, jus frais. Pas cher, délicieux, et c’est là que mangent les Singapouriens. Culture inscrite à l’UNESCO." },
        { k: "repas", h: "Soir", t: "Hotpot chez Hai Di Lao, Clarke Quay", p: "Un hotpot sichuanais : chacun fait cuire viande, légumes et nouilles dans un bouillon qui mijote au milieu de la table. Avec en prime le spectacle des nouilles étirées à la main. Ensuite, balade au bord de la rivière entre les bars illuminés." },
      ] },
    { d: "2026-12-16", pays: "vn", etape: "Singapour → Hanoï", titre: "Cap sur le Vietnam", img: "water-puppets", cle: "✈️ 13h25 → 15h45",
      resume: "Un vol de jour, puis le vieux quartier de Hanoï, des marionnettes sur l’eau et un bún chả mémorable.",
      items: [
        { k: "taxi", h: "~10h30", t: "Direction Changi", p: "Si on a un peu d’avance : un coup d’œil au Jewel, la plus haute cascade intérieure du monde, au cœur de l’aéroport." },
        { k: "vol", h: "13h25", t: "Singapour → Hanoï", p: "Vietnam Airlines, arrivée à 15h45 (une heure de moins qu’à Singapour)." },
        { k: "taxi", h: "~16h30", t: "Taxi de Nội Bài au vieux quartier", p: "Environ 45 minutes. Sortez une veste : les soirées de décembre sont fraîches à Hanoï." },
        { k: "visite", h: "Fin d’après-midi", t: "Le lac Hoàn Kiếm et le vieux quartier", p: "Le tour du lac à la tombée du jour, le pont rouge Thê Húc vers le temple de Ngọc Sơn, puis les ruelles où chaque rue avait son métier : soie, métal, papier votif. Attention aux scooters : traversez d’un pas régulier !" },
        { k: "spectacle", h: "Soirée", t: "Les marionnettes sur l’eau", p: "Un art né dans les rizières du delta du fleuve Rouge il y a près de mille ans. Cachés derrière un rideau de bambou, les marionnettistes font danser dragons, pêcheurs et buffles sur un bassin, au son d’un orchestre traditionnel. Le théâtre Thăng Long est au bord du lac ; le spectacle dure environ 50 minutes." },
        { k: "repas", h: "Dîner", t: "Bún chả chez Hương Liên", p: "Le plat emblématique de Hanoï : du porc grillé au charbon dans un bouillon aigre-doux, avec vermicelles de riz et herbes fraîches. Barack Obama et Anthony Bourdain y ont dîné en 2016 ; le menu porte encore leur nom." },
        { k: "nuit", t: "Nuit dans un hôtel au cœur du vieux quartier." },
      ] },
    { d: "2026-12-17", pays: "vn", etape: "Baie d’Along", titre: "Une nuit sur la baie", img: "halong-cruise", cle: "🛳️ Croisière · 1 nuit",
      resume: "Près de 2 000 îlots calcaires classés à l’UNESCO, et une nuit à bord en suite pour nous trois.",
      items: [
        { k: "taxi", h: "7h30", t: "Départ de l’hôtel en minibus", p: "Environ 2h30 de route par l’autoroute, avec une pause en chemin." },
        { k: "bateau", h: "Fin de matinée", t: "Embarquement et déjeuner à bord", p: "Installation dans la cabine pendant que le bateau s’enfonce dans la baie. Programme habituel : kayak ou barque entre les pitons, visite d’une grotte, coucher de soleil sur le pont, cours de cuisine et dîner. Le programme exact sera annoncé à bord." },
        { k: "nuit", t: "Nuit à bord, au milieu de la baie." },
      ] },
    { d: "2026-12-18", pays: "vn", etape: "Baie d’Along → Hội An", titre: "Retour à terre, cap sur Hội An", img: "kayak", cle: "✈️ 18h20 → 19h45",
      note: "La journée a une seule vraie contrainte : le vol de 18h20.",
      resume: "Lever de soleil sur la baie, puis minibus, taxi et vol vers le centre du Vietnam.",
      items: [
        { k: "bateau", h: "Lever du soleil", t: "Le matin sur la baie", p: "Tai-chi sur le pont pour ceux qui le veulent, brunch et dernière navigation avant de rentrer au port." },
        { k: "taxi", h: "~14h00", t: "Minibus, puis taxi pour l’aéroport", p: "La navette nous dépose vers 14h à l’est de Hanoï, et on file en taxi à l’aéroport (environ 45 minutes). On a largement le temps." },
        { k: "vol", h: "18h20", t: "Hanoï → Đà Nẵng", p: "Arrivée à 19h45, puis environ 45 minutes de route jusqu’à Hội An. Dîner tardif." },
        { k: "nuit", t: "Nuit dans un hôtel à Hội An (2 nuits)." },
      ] },
    { d: "2026-12-19", pays: "vn", etape: "Hội An", titre: "La ville aux lanternes", img: "hoian-bridge", cle: "🏮 Lanternes · spectacle",
      resume: "Vieille ville à pied le matin, repos l’après-midi, puis la rivière illuminée et un grand spectacle.",
      items: [
        { k: "visite", h: "Matin", t: "Maisons jaunes et pont japonais", p: "Le pont couvert japonais (Chùa Cầu), symbole de la ville, vieux d’environ quatre siècles. Les maisons de marchands et salles d’assemblée chinoises, le marché central et les quais de la rivière Thu Bồn. Idée : Hội An est célèbre pour ses tailleurs : un vêtement commandé le matin peut être prêt le lendemain." },
        { k: "repas", h: "Midi", t: "Les spécialités locales", p: "Cao lầu (nouilles épaisses au porc, introuvables ailleurs), bánh mì de Hội An (souvent élu meilleur sandwich du pays) et white rose, de petits raviolis aux crevettes." },
        { k: "visite", h: "Après-midi", t: "Repos, vélo ou plage", p: "Une pause à l’hôtel, une balade à vélo dans les rizières, ou la plage d’An Bàng, à 15 minutes." },
        { k: "visite", h: "Tombée de la nuit", t: "Les lanternes sur la rivière", p: "La vieille ville s’illumine. On peut déposer une petite lanterne flottante sur la rivière et faire un vœu." },
        { k: "spectacle", h: "Soirée", t: "Hội An Memories Show", p: "Un grand spectacle en plein air sur une île de la rivière, avec des centaines d’artistes. Il raconte quatre siècles d’histoire de Hội An, de l’âge d’or du port à aujourd’hui. Grandiose. Billets à réserver." },
      ] },
    { d: "2026-12-20", pays: "th", etape: "Hội An → Phuket", titre: "Bienvenue en Thaïlande", img: "patong-sunset", cle: "✈️ 12h00 → 17h50",
      resume: "Un transfert, un vol et le premier dîner thaï, face aux couchers de soleil de la mer d’Andaman.",
      items: [
        { k: "taxi", h: "~9h15", t: "Route de Hội An vers l’aéroport de Đà Nẵng", p: "Environ 45 minutes. Il faut partir vers 9h15." },
        { k: "vol", h: "12h00", t: "Đà Nẵng → Phuket", p: "Atterrissage à 17h50 (heure locale ; Vietnam et Thaïlande sont à la même heure)." },
        { k: "taxi", t: "Taxi jusqu’à Patong", p: "Environ 1 heure de route à travers l’île." },
        { k: "repas", h: "Soir", t: "Dîner thaï pour fêter l’arrivée", p: "Pad thaï, curry vert, salade de papaye. Demandez « mai phet » : pas épicé 😉" },
        { k: "nuit", t: "Nuit dans un resort à Patong (2 nuits)." },
      ] },
    { d: "2026-12-21", pays: "th", etape: "Patong", titre: "Une vraie journée de vacances", img: "patong", cle: "🏖️ Plage & massage",
      resume: "La première journée sans avion ni bateau depuis longtemps !",
      items: [
        { k: "visite", h: "Journée", t: "Plage, piscine, massage thaï", p: "Des massages partout, pour pas cher. Idées d’escapade si l’envie vient : le Big Buddha sur sa colline, les points de vue de Karon, les maisons sino-portugaises de la vieille ville de Phuket." },
        { k: "repas", h: "Soir", t: "Coucher de soleil et fruits de mer", p: "Dîner presque les pieds dans l’eau. Les curieux peuvent faire un tour sur Bangla Road, la rue la plus animée de Phuket." },
      ] },
    { d: "2026-12-22", pays: "th", etape: "Patong → Koh Yao Yai", titre: "Traversée vers l’île", img: "longtail", cle: "🚤 Hors-bord ~11h00",
      note: "Horaire du hors-bord à confirmer.",
      resume: "Une heure de route, vingt minutes de bateau, et l’on s’installe pour trois nuits face aux pitons.",
      items: [
        { k: "taxi", h: "Matin", t: "Patong → marina d’Ao Por", p: "Environ 45 minutes de route jusqu’à la côte est de Phuket. On arrive tôt au ponton." },
        { k: "bateau", h: "~11h00", t: "Hors-bord vers Koh Yao Yai", p: "Vingt minutes de traversée entre les îles. Horaire à confirmer." },
        { k: "nuit", t: "Nuit dans un resort sur l’île (3 nuits)." },
      ] },
    { d: "2026-12-23", pays: "th", etape: "Koh Yao Yai", titre: "Rien d’obligatoire", img: "yao-palms", cle: "🌴 Farniente",
      resume: "Piscine, plage, kayak, tour de l’île : l’opposé de Patong.",
      items: [
        { k: "visite", h: "Journée", t: "Au choix", p: "Piscine, plage, lecture, sieste. Kayak ou paddle face aux pitons. Tour de l’île à vélo ou en scooter-taxi à travers villages et rizières. Excursion possible en bateau à longue queue vers les îles voisines." },
        { k: "info", t: "À savoir", p: "L’île est majoritairement musulmane : dans les villages, on se couvre les épaules et les genoux." },
      ] },
    { d: "2026-12-24", pays: "th", etape: "Koh Yao Yai", titre: "Réveillon de Noël 🎄", img: "phang-nga", cle: "🎄 Dîner de Noël",
      resume: "Un dernier bain de mer avant le dîner, face à la mer.",
      items: [
        { k: "visite", h: "Journée", t: "Noël au soleil", p: "Une journée tranquille avant la fête." },
        { k: "repas", h: "Soir", t: "Le dîner de Noël", p: "Au resort, face à la mer. Le programme de la soirée sera annoncé par l’hôtel (à confirmer). Prévoyez une tenue un peu habillée !" },
      ] },
    { d: "2026-12-25", pays: "th", etape: "Koh Yao Yai → Phuket", titre: "Joyeux Noël, retour à Phuket", img: "nai-yang", cle: "🚤 Hors-bord ~10h30",
      note: "Horaire du hors-bord à confirmer.",
      resume: "Petit-déjeuner de Noël, traversée, puis une dernière soirée thaïe près de l’aéroport.",
      items: [
        { k: "bateau", h: "~10h30", t: "Hors-bord vers Ao Por", p: "Petit-déjeuner de Noël, puis traversée et route vers le nord de l’île, près de l’aéroport. Horaire à confirmer." },
        { k: "visite", h: "Après-midi & soir", t: "Dernière soirée thaïe", p: "On reste au calme près de l’aéroport. La plage de Nai Yang est tout près : on y voit les avions atterrir au-dessus de la mer au coucher du soleil. Dîner simple et coucher tôt." },
        { k: "nuit", t: "Nuit dans un hôtel près de l’aéroport." },
      ] },
    { d: "2026-12-26", pays: "fr", etape: "Phuket → Singapour → Paris", titre: "Grande journée de vol", cle: "✈️ 8h40 → 11h40 · 14h00 → ~21h00",
      resume: "Tous les trois jusqu’à Singapour, où Fanny dit au revoir, puis Maman et Quentin continuent vers Paris.",
      items: [
        { k: "vol", h: "8h40", t: "Phuket → Singapour (tous les trois)", p: "Arrivée à 11h40 à Changi. C’est là que Fanny vous dit au revoir 🥲" },
        { k: "vol", h: "14h00", t: "Singapour → Paris CDG (Maman & Quentin)", p: "Vol de jour, arrivée à Roissy vers 21h le soir même." },
        { k: "nuit", t: "Nuit dans un hôtel à l’aéroport CDG, relié aux terminaux par le CDG VAL." },
      ] },
    { d: "2026-12-27", pays: "fr", etape: "Roissy → la maison", titre: "Trains pour rentrer", cle: "🚆 Trains à réserver",
      resume: "Dix minutes de CDG VAL jusqu’à la gare TGV, puis chacun rentre chez soi.",
      items: [
        { k: "train", h: "Matin", t: "Maman : CDG TGV → Lorraine TGV", p: "Train du matin (billet à réserver)." },
        { k: "train", h: "~2 h plus tard", t: "Quentin : CDG TGV → Montpellier", p: "Environ deux heures après Maman (billet à réserver)." },
      ] },
  ],

  // À voir : étape → liste
  voir: [
    { e: "sg", n: "Gardens by the Bay", img: "supertrees", big: true, duree: "demi-journée", jour: "14 déc.",
      t: "Les « super-arbres » géants, la montagne sous serre du Cloud Forest et le Flower Dome décoré pour Noël. À la nuit tombée, spectacle de lumière gratuit au Supertree Grove." },
    { e: "sg", n: "Marina Bay", img: "marina-bay", duree: "soirée", jour: "14 déc.",
      t: "La baie vue d’en haut, depuis la terrasse d’une brasserie au 33e étage, avec le Marina Bay Sands juste en face." },
    { e: "sg", n: "Cloud Forest", img: "cloud-forest", duree: "1 h 30", jour: "14 déc.",
      t: "Une montagne couverte de plantes, une cascade intérieure de plus de 30 mètres et des passerelles suspendues. Au frais !" },
    { e: "sg", n: "Chinatown, Little India, Kampong Glam", img: "little-india", duree: "matinée", jour: "15 déc.",
      t: "Temples chinois et hindous, mosquée du Sultan, rues colorées : trois cultures à quelques stations de métro." },
    { e: "sg", n: "Clarke Quay", img: "clarke-quay", duree: "soirée", jour: "15 déc.",
      t: "Les quais de la rivière, illuminés le soir, après le dîner." },
    { e: "sg", n: "Jewel Changi", img: "jewel", duree: "30 min", jour: "16 déc.",
      t: "Au cœur de l’aéroport, la plus haute cascade intérieure du monde. Le dernier coup d’œil avant de s’envoler." },

    { e: "hn", n: "Lac Hoàn Kiếm & pont Thê Húc", img: "the-huc", duree: "1 h", jour: "16 déc.",
      t: "Le tour du lac à la tombée du jour et le pont rouge qui mène au temple de Ngọc Sơn." },
    { e: "hn", n: "Le vieux quartier", img: "hanoi-old-quarter", big: true, duree: "soirée", jour: "16 déc.",
      t: "Les « 36 rues », où chaque rue avait son métier. Scooters, étals, odeurs de cuisine : Hanoï à l’état pur." },
    { e: "hn", n: "Marionnettes sur l’eau", img: "water-puppets", duree: "50 min", jour: "16 déc.",
      t: "Un art vieux de près de mille ans : dragons, pêcheurs et buffles dansent sur un bassin, au son d’un orchestre traditionnel." },
    { e: "hl", n: "La baie d’Along", img: "halong", big: true, duree: "1 nuit", jour: "17 – 18 déc.",
      t: "Près de 2 000 îles et îlots calcaires sortant de l’eau émeraude, au patrimoine mondial de l’UNESCO. Décembre, frais et sec, est une belle saison." },
    { e: "hl", n: "Kayak entre les pitons", img: "kayak", duree: "1 h", jour: "17 déc.",
      t: "Pagayer dans le silence, entre les rochers et les grottes. Selon le programme du bateau." },
    { e: "ha", n: "Le pont couvert japonais", img: "hoian-bridge", duree: "30 min", jour: "19 déc.",
      t: "Le symbole de Hội An, vieux d’environ quatre siècles, au cœur de la vieille ville classée à l’UNESCO." },
    { e: "ha", n: "La vieille ville aux murs jaunes", img: "hoian-walls", big: true, duree: "matinée", jour: "19 déc.",
      t: "Maisons de marchands, salles d’assemblée chinoises, marché et quais de la rivière. Et des tailleurs partout." },
    { e: "ha", n: "Les lanternes sur la rivière", img: "lantern-boats", duree: "soirée", jour: "19 déc.",
      t: "À la nuit tombée, des milliers de lanternes de soie. On peut déposer une petite lanterne flottante et faire un vœu." },
    { e: "ha", n: "Plage d’An Bàng", img: "an-bang", duree: "à la carte", jour: "19 déc.",
      t: "À 15 minutes de la vieille ville, une longue plage pour l’après-midi si l’envie d’eau salée se fait sentir." },

    { e: "pa", n: "Plage de Patong", img: "patong", big: true, duree: "journée", jour: "21 déc.",
      t: "La baie la plus animée de Phuket : un grand arc de sable et des couchers de soleil sur la mer d’Andaman." },
    { e: "pa", n: "Le Big Buddha", img: "big-buddha", duree: "1 h 30", jour: "idée · 21 déc.",
      t: "Une statue de 45 mètres sur une colline, avec une vue à 360° sur l’île. Idée d’escapade." },
    { e: "pa", n: "La vieille ville de Phuket", img: "phuket-old-town", duree: "demi-journée", jour: "idée · 21 déc.",
      t: "Maisons sino-portugaises colorées, cafés et galeries. Un autre visage de Phuket, loin de la plage." },
    { e: "ky", n: "Koh Yao Yai", img: "phang-nga", big: true, duree: "3 nuits", jour: "22 – 25 déc.",
      t: "Une grande île paisible, entre Phuket et Krabi, au milieu de la baie de Phang Nga : villages de pêcheurs, hévéas, plages tranquilles face aux pitons." },
    { e: "ky", n: "Bateau à longue queue", img: "longtail", duree: "demi-journée", jour: "idée · 23 déc.",
      t: "Excursion possible vers les îles voisines à bord des bateaux traditionnels thaïs." },
    { e: "ky", n: "Nai Yang", img: "nai-yang", duree: "soirée", jour: "25 déc.",
      t: "Près de l’aéroport : on y voit les avions atterrir au-dessus de la mer au coucher du soleil." },
  ],

  // À table
  table: [
    { p: "sg", n: "Poulet hainanais", loc: "Hainanese chicken rice", img: "chicken-rice", quand: "hawker centre · 15 déc.",
      t: "Le plat national, d’une simplicité trompeuse : poulet poché, riz cuit dans le bouillon, sauce gingembre et piment." },
    { p: "sg", n: "Laksa", loc: "Katong laksa", img: "laksa", quand: "hawker centre · 15 déc.",
      t: "Nouilles dans un bouillon au lait de coco, crevettes et piment. Parfumé, réconfortant, un peu piquant." },
    { p: "sg", n: "Kaya toast & œufs mollets", loc: "Kaya toast", img: "kaya-toast", quand: "petit-déjeuner · 14 déc.",
      t: "Du pain grillé tartiné de confiture de coco et de beurre, à tremper dans des œufs mollets au soja poivré." },
    { p: "vn", n: "Bún chả", loc: "Bún chả Hà Nội", img: "bun-cha", quand: "dîner · 16 déc.",
      t: "Le plat de Hanoï : porc grillé au charbon dans un bouillon aigre-doux, vermicelles de riz et herbes fraîches." },
    { p: "vn", n: "Phở", loc: "Phở bò", img: "pho", quand: "à Hanoï, dès le matin",
      t: "La soupe de bœuf aux nouilles de riz que les Hanoïens mangent dès le matin. Bouillon parfumé à la badiane et au gingembre." },
    { p: "vn", n: "Café à l’œuf", loc: "Cà phê trứng", img: "egg-coffee", quand: "une pause à Hanoï · 16 déc.",
      t: "Une spécialité de Hanoï : un café fort coiffé d’une crème d’œuf battu et de lait concentré sucré. Un dessert en tasse." },
    { p: "vn", n: "Cao lầu", loc: "Cao lầu", img: "cao-lau", quand: "déjeuner · 19 déc.",
      t: "Des nouilles épaisses au porc, aux herbes et au croustillant, qu’on ne trouve vraiment qu’à Hội An." },
    { p: "vn", n: "White rose", loc: "Bánh bao bánh vạc", img: "white-rose", quand: "déjeuner · 19 déc.",
      t: "De petits raviolis translucides aux crevettes, en forme de rose. Une spécialité de Hội An." },
    { p: "vn", n: "Bánh mì", loc: "Bánh mì Hội An", img: "banh-mi", quand: "n’importe quand · 19 déc.",
      t: "La baguette vietnamienne garnie de viande, de pâté, de crudités et d’herbes. Celui de Hội An est célèbre dans tout le pays." },
    { p: "th", n: "Pad thaï", loc: "ผัดไทย", img: "pad-thai", quand: "premier dîner · 20 déc.",
      t: "Les nouilles de riz sautées aux crevettes, cacahuètes et citron vert. Le classique d’arrivée." },
    { p: "th", n: "Salade de papaye", loc: "Som tam · ส้มตำ", img: "som-tam", quand: "à la plage · 21 déc.",
      t: "Papaye verte pilée au mortier, citron vert, tomates et piment. Demandez « mai phet » : pas épicé 😉" },
    { p: "th", n: "Tom yum", loc: "Tom yum goong · ต้มยำกุ้ง", img: "tom-yum", quand: "dîner de fruits de mer · 21 déc.",
      t: "La soupe de crevettes citronnelle, galanga, citron vert et piment : acide, parfumée, piquante." },
    { p: "th", n: "Curry vert", loc: "Kaeng khiao wan · แกงเขียวหวาน", img: "green-curry", quand: "à l’île · 23 déc.",
      t: "Un curry au lait de coco, basilic thaï et aubergines. Plus doux qu’il n’en a l’air, sauf si on insiste." },
    { p: "th", n: "Riz gluant à la mangue", loc: "Khao niao mamuang · ข้าวเหนียวมะม่วง", img: "mango-sticky-rice", quand: "le dessert de Noël",
      t: "Du riz gluant au lait de coco servi avec de la mangue mûre. Le dessert thaï par excellence." },
  ],
  conseilsTable: [
    "Les stands bondés sont les meilleurs : beaucoup de rotation, c’est frais.",
    "On boit de l’eau en bouteille, et on se méfie des glaçons dans les petits stands.",
    "Un petit paquet de mouchoirs et un flacon de gel dans le sac : tous les stands n’ont pas de serviettes.",
    "« Pas pimenté » : au Vietnam « không cay », en Thaïlande « mai phet ».",
  ],

  // Vols (cartes d'embarquement)
  vols: [
    { j: "2026-12-12", de: "CDG", dl: "Paris", a: "SIN", al: "Singapour", dep: "22h20", arr: "18h05 (+1)", qui: "Maman, Quentin" },
    { j: "2026-12-16", de: "SIN", dl: "Singapour", a: "HAN", al: "Hanoï", dep: "13h25", arr: "15h45", qui: "Tous les trois" },
    { j: "2026-12-18", de: "HAN", dl: "Hanoï", a: "DAD", al: "Đà Nẵng", dep: "18h20", arr: "19h45", qui: "Tous les trois" },
    { j: "2026-12-20", de: "DAD", dl: "Đà Nẵng", a: "HKT", al: "Phuket", dep: "12h00", arr: "17h50", qui: "Tous les trois" },
    { j: "2026-12-26", de: "HKT", dl: "Phuket", a: "SIN", al: "Singapour", dep: "8h40", arr: "11h40", qui: "Tous les trois" },
    { j: "2026-12-26", de: "SIN", dl: "Singapour", a: "CDG", al: "Paris", dep: "14h00", arr: "~21h00", qui: "Maman, Quentin" },
  ],
  trains: [
    { j: "2026-12-11", qui: "Quentin", t: "Montpellier Sud de France → Paris Gare de Lyon", h: "18h50 → 22h04" },
    { j: "2026-12-12", qui: "Maman", t: "Lorraine TGV → aéroport CDG", h: "10h39 → 12h00" },
    { j: "2026-12-27", qui: "Maman", t: "Aéroport CDG → Lorraine TGV", h: "le matin · à réserver" },
    { j: "2026-12-27", qui: "Quentin", t: "Aéroport CDG → Montpellier", h: "~2 h après Maman · à réserver" },
  ],

  formalites: [
    { t: "Passeport valide au moins 6 mois après le retour", p: "Donc jusqu’à fin juin 2027 au minimum. À vérifier dès maintenant !" },
    { t: "Singapour : pas de visa", p: "La SG Arrival Card se remplit en ligne dans les 3 jours avant l’arrivée. Elle est gratuite sur le site officiel de l’immigration (ICA)." },
    { t: "Vietnam : pas de visa pour un court séjour touristique", p: "Les règles seront revérifiées avant le départ." },
    { t: "Thaïlande : pas de visa", p: "La carte d’arrivée numérique TDAC se remplit en ligne dans les 3 jours avant l’arrivée. Elle aussi est gratuite sur le site officiel." },
  ],
  alerte: "Il existe des sites payants qui imitent les formulaires officiels : Fanny vous enverra les bons liens le moment venu.",

  meteo: [
    { l: "Singapour", i: "⛅", t: "30–32 °C", p: "Chaud et humide, averses courtes (mousson)", lo: 30, hi: 32 },
    { l: "Hanoï", i: "🌥️", t: "21–26 °C", p: "Sec, un peu frais le soir (14–20 °C la nuit)", lo: 14, hi: 26 },
    { l: "Baie d’Along", i: "🌫️", t: "18–22 °C", p: "Frais et sec, idéal pour la croisière", lo: 18, hi: 22 },
    { l: "Hội An", i: "🌦️", t: "23–24 °C", p: "Fin de la saison des pluies : averses possibles", lo: 23, hi: 24 },
    { l: "Phuket & Koh Yao Yai", i: "☀️", t: "29–32 °C", p: "Saison sèche, grand beau", lo: 29, hi: 32 },
  ],
  valise: [
    "Des vêtements légers, pour 8 jours — on fera une lessive à Hội An",
    "De quoi avoir chaud le soir à Hanoï et sur la baie d’Along (14–20 °C)",
    "Un imperméable léger pour Hội An",
    "Deux maillots de bain, lunettes de soleil, chapeau",
    "Crème solaire indice élevé",
    "Une tenue un peu habillée pour le réveillon 🎄",
    "Des chaussures confortables pour marcher, et des sandales",
    "Vos médicaments habituels, avec l’ordonnance",
    "La batterie externe, en bagage à main (jamais en soute)",
    "Un sac étanche pour les traversées en hors-bord vers l’île",
    "Passeport et copie numérique — Fanny s’occupe des cartes d’arrivée, de l’eSIM et des adaptateurs",
    "🚫 Pas de cigarette électronique : elle est interdite à Singapour comme en Thaïlande",
  ],
  infos: [
    { i: "💳", t: "Carte bancaire", p: "Acceptée presque partout à Singapour. Prévenez votre banque de votre voyage." },
    { i: "💵", t: "Espèces", p: "Utiles au Vietnam et en Thaïlande pour les petits achats. On retire sur place, aux distributeurs. Ordre de grandeur : 30 000 ₫ ≈ 1 € · 38 ฿ ≈ 1 € · 1 S$ ≈ 0,70 €." },
    { i: "💊", t: "Médicaments", p: "Singapour est strict : codéine, somnifères, certains traitements anxiolytiques ou pour le TDAH demandent une autorisation préalable, gratuite et à faire en ligne avant le départ. Dites-le à Fanny si c’est votre cas." },
    { i: "📱", t: "Téléphone", p: "Une eSIM « Asie du Sud-Est » avec des données évite les frais d’itinérance. Fanny peut vous aider à l’installer." },
    { i: "🔌", t: "Prises", p: "À Singapour, prises anglaises à trois broches : adaptateur indispensable. Au Vietnam et en Thaïlande, les prises françaises passent le plus souvent." },
    { i: "🕐", t: "Décalage horaire", p: "+7 h à Singapour, +6 h au Vietnam et en Thaïlande, par rapport à la France." },
    { i: "💧", t: "Eau", p: "On boit de l’eau en bouteille partout, sauf à Singapour où l’eau du robinet est potable." },
  ],
  mots: [
    { p: "vn", f: "Bonjour", l: "Xin chào", r: "sin tchao" },
    { p: "vn", f: "Merci", l: "Cảm ơn", r: "kam eun" },
    { p: "vn", f: "C’est délicieux !", l: "Ngon quá!", r: "ngon coua" },
    { p: "vn", f: "Pas pimenté", l: "Không cay", r: "khoung kaï" },
    { p: "th", f: "Bonjour", l: "Sawatdee khrap / kha", r: "khrap (homme) · kha (femme)" },
    { p: "th", f: "Merci", l: "Khop khun khrap / kha", r: "kop koun" },
    { p: "th", f: "C’est délicieux !", l: "Aroi mak!", r: "aroï mak" },
    { p: "th", f: "Pas épicé", l: "Mai phet", r: "maï pet" },
  ],
};
